#████████╗██╗███╗░░░███╗░█████╗░░█████╗░██╗░░░██╗████████╗░█████╗░███╗░░░███╗███████╗░██████╗░██████╗░█████╗░░██████╗░███████╗
#╚══██╔══╝██║████╗░████║██╔══██╗██╔══██╗██║░░░██║╚══██╔══╝██╔══██╗████╗░████║██╔════╝██╔════╝██╔════╝██╔══██╗██╔════╝░██╔════╝
#░░░██║░░░██║██╔████╔██║███████║███████║██║░░░██║░░░██║░░░██║░░██║██╔████╔██║█████╗░░╚█████╗░╚█████╗░███████║██║░░██╗░█████╗░░
#░░░██║░░░██║██║╚██╔╝██║██╔══██║██╔══██║██║░░░██║░░░██║░░░██║░░██║██║╚██╔╝██║██╔══╝░░░╚═══██╗░╚═══██╗██╔══██║██║░░╚██╗██╔══╝░░
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██║░░██║╚██████╔╝░░░██║░░░╚█████╔╝██║░╚═╝░██║███████╗██████╔╝██████╔╝██║░░██║╚██████╔╝███████╗
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░╚═════╝░░░░╚═╝░░░░╚════╝░╚═╝░░░░░╚═╝╚══════╝╚═════╝░╚═════╝░╚═╝░░╚═╝░╚═════╝░╚══════╝
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#
#Интервал отправки сообщений в секундах
interval: 1
#
#и кароче если порядок сообщения с 1 начнешь а не как тут щя с 0
#то плагин сломается
#я конечно мог сделать с 1, но мне лень так что нюхач бебри
#
#сообщения кстати отправляются в рандомном порядке
messages:
  0:
    - '&a╔'
    - '&a║ &eПокупайте донат!!!'
    - '&a║ &eУ нас на сайте скидки!!!'
    - '&a║ &8(Нажми) &ehttp://easydonate.pochinite.api/please'
    - '&a╚'
  1:
    - '&a╔'
    - '&a║ &eСкай варс хуже бед варса!!!'
    - '&a║ &eУ нас на сайте скидки!!!'
    - '&a║ &8(Нажми) &ehttp://easydonate.pochinite.api/please'
    - '&a╚'
  2:
    - '&a╔'
    - '&a║ &eВиталий почините апи!!!'
    - '&a║ &eУ нас на сайте скидки!!!'
    - '&a║ &8(Нажми) &ehttp://easydonate.pochinite.api/please'
    - '&a╚'
  3:
    - '&a╔'
    - '&a║ &eСамый крутой донатер тот кто много задонатил!!!'
    - '&a║ &eУ нас на сайте скидки!!!'
    - '&a║ &8(Нажми) &ehttp://easydonate.pochinite.api/please'
    - '&a╚'
  4:
    - '&a╔'
    - '&a║ &eAPIを修正してください'
    - '&a║ &eУ нас на сайте скидки!!!'
    - '&a║ &8(Нажми) &ehttp://easydonate.pochinite.api/please'
    - '&a╚'
#
#thanks for use my plugin <3